// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct ip s_ip = {"192.168.4.1", "192.168.4.1"};
void glue_get_ip(struct ip *data) {
  *data = s_ip;  // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct gerenciar_celula s_gerenciar_celula = {true, true, true, false, false, false, true, true, true, true, true, false};
void glue_get_gerenciar_celula(struct gerenciar_celula *data) {
  *data = s_gerenciar_celula;  // Sync with your device
}
void glue_set_gerenciar_celula(struct gerenciar_celula *data) {
  s_gerenciar_celula = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct config s_config = {false, 1, 0.5};
void glue_get_config(struct config *data) {
  *data = s_config;  // Sync with your device
}
void glue_set_config(struct config *data) {
  s_config = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct wifi s_wifi = {"pass_novo", "ssid_novo", "pass_atual", "ssid_atual"};
void glue_get_wifi(struct wifi *data) {
  *data = s_wifi;  // Sync with your device
}
void glue_set_wifi(struct wifi *data) {
  s_wifi = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct texto s_texto = {"Desconectado"};
void glue_get_texto(struct texto *data) {
  *data = s_texto;  // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct resumo s_resumo = {50, 200.5, 100.5, 12};
void glue_get_resumo(struct resumo *data) {
  *data = s_resumo;  // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct tensoes s_tensoes = {12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1};
void glue_get_tensoes(struct tensoes *data) {
  *data = s_tensoes;  // Sync with your device
}
